
###
POST http://localhost:3000/contratos/
Content-Type: application/json


{
  "nombre": "Julio",
  "apellido1": "Salinas",
  "apellido2": "Lujero",
  "documento": "nif",
  "cp": "46022",
  "localidad": "Valencia",
  "direccion": "Avenida Pío- 20",
  "telefono":"688237111"
}

###
GET http://localhost:3000/contratos/
###

GET http://localhost:3000/contratos/63c6dc5cab4c5e2bfd5288de




###
PUT http://localhost:3000/contratos/63c6dc5cab4c5e2bfd5288de
Content-Type: application/json

{
    "nombre": "Javierito",
    "apellido1": "Moyaaa",
    "apellido2": "Simooo",
    "documento": "nif",
    "cp": "46011",
    "localidad": "Valencia",
    "direccion": "Calle Serreria- 20",
    "telefono": "644234111"
    }



###
DELETE http://localhost:3000/contratos/63c6dc5cab4c5e2bfd5288de
